/**
 *
 * @author Jatin Ambasana
 */
import java.sql.*;
public class CreateInsert_Example 
{
public static void main(String[] args)
{ 
    try 
    {    
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = 
            DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb1","root","");
        
        Statement s = con.createStatement();
        
        // create a table
        s.execute("Create table Employee " 
                + "( Emp_id int, Emp_name varchar(20), Emp_address varchar(30) )" ); 
        System.out.println("TABLE CREATED SUCCESSFULLY");
        System.out.println("");
        
        // insert rows into the table
        s.execute("insert into Employee values(001,'ARman','Delhi')");  
        s.execute("insert into Employee values(002,'Robert','Canada')"); 
        s.execute("insert into Employee values(003,'Ahuja','Karnal')");  
        
        // Retrieve the data from the table
        s.execute("select * from Employee"); 
        ResultSet rs = s.getResultSet(); // get the ResultSet generated by our query
        if (rs != null) // if rs == null, then there is no record in ResultSet to show
            while ( rs.next() ) // By this line we will iterated through the data row-by-row
            { 
                System.out.println("________________________________________" );
                System.out.println("Id of the Employee: " + rs.getString(1) );
                System.out.println("Name of Employee: " + rs.getString(2) );
                System.out.println("Address of Employee: " + rs.getString(3) );
                System.out.println("________________________________________" );
            }
        s.close(); // close the Statement to let the database know we're done with it
        con.close(); // close the Connection to let the database know we're done with it
    }
    catch (Exception err) 
    {
        System.out.println("ERROR: " + err);
    }
}
}
